services:
  app:
    build: .
    ports:
      - "8443:443"
    volumes:
      - .:/var/www/html
      - ./docker/certs:/etc/apache2/ssl:ro
    networks:
      - laravel-net
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - laravel-net

networks:
  laravel-net:

volumes:
  mysql-data:
